<a href="https://colab.research.google.com/github/Nsquare1994/COT5600/blob/master/COT5600_HW1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np
import scipy.linalg

m = np.array([[1, 1, 3, 4],[-1, 1, 5, 6],[0, 0, 1, 2],[0, 0, 3, 2]])

#test if poly annihilates with M
# if (M-root*I) is 0
#poly annihilates with M
def annihilate_poly(m):
  #compute the poly of matrix M
  poly = np.poly(m)
  #root of poly
  root = np.roots(poly)
  print(m)
  print(poly)
  print(root)
  root = root.reshape(2,2)
  print(root)
  #print(np.identity(m.ndim))
  #print(m-(root*np.identity(m.ndim)))

annihilate_poly(m)

[[ 1  1  3  4]
 [-1  1  5  6]
 [ 0  0  1  2]
 [ 0  0  3  2]]
[ 1. -5.  4.  2. -8.]
[ 4.+0.j  1.+1.j  1.-1.j -1.+0.j]
[[ 4.+0.j  1.+1.j]
 [ 1.-1.j -1.+0.j]]
