<a href="https://colab.research.google.com/github/Nsquare1994/COT5600/blob/master/COT_5600_HW3_1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [9]:
#problem 1 fourier

import numpy as np

def get_fourier_matrix(N):

  omega = np.exp((2*np.pi*1j)/N)
  
  return np.asarray([[(omega**(i*j))/np.sqrt(N) for i in range(N)] for j in range(N)])
 

def check_unitary(N):
  N = np.asarray(N)
  return(np.allclose(np.eye(N.shape[0]), N.dot(N.conj().T)))

def four_power(N):
  return np.allclose(np.eye(N.shape[0]), np.linalg.matrix_power(N, 4))

def e_value(N):
  fourier = get_fourier_matrix(N)
  i, j = np.linalg.eig(fourier)
  return np.round(i)

print("Testing with 3")
print(get_fourier_matrix(3))
print(check_unitary(get_fourier_matrix(3)))
print(four_power(get_fourier_matrix(3)))
print(e_value(3))

[[ 0.57735027+0.j   0.57735027+0.j   0.57735027+0.j ]
 [ 0.57735027+0.j  -0.28867513+0.5j -0.28867513-0.5j]
 [ 0.57735027+0.j  -0.28867513-0.5j -0.28867513+0.5j]]
True
True
[ 1.+0.j -1.+0.j  0.+1.j]


In [17]:
#problem 2 cyclic

import numpy as np

def get_fourier_matrix(N):
  omega = np.exp((2*np.pi*1j)/N)
  return np.asarray([[(omega**(i*j))/np.sqrt(N) for i in range(N)] for j in range(N)])

def get_cyclic_shift_matrix(N):
  m = np.zeros((N, N))
  for i in range(N):
    for j in range(N):
      if(j == ((i+1)%N)):
        m[i][j] = 1
  return m

def check_unitary(N):
  N = np.asarray(N)
  return(np.allclose(np.eye(N.shape[0]), N.dot(N.conj().T)))

def N_power(N, nPower):
  return np.allclose(np.eye(N.shape[0]), np.linalg.matrix_power(N, nPower))

def e_value(N):
  c = get_cyclic_shift_matrix(N)
  i, j = np.linalg.eig(c)
  return np.round(i)

def diagonal(N):
  c = get_cyclic_shift_matrix(N)
  f = get_fourier_matrix(N)
  d = np.dot(np.conj(f).T, np.dot(c, f))
  for i in range(0, N): 
        for j in range(0, N) : 
              
    
            if ((i != j) and
             (d[i][j] != 0)) : 
                return False
  
  return True

print(get_cyclic_shift_matrix(4))
print(check_unitary(get_cyclic_shift_matrix(4)))
print(N_power(get_cyclic_shift_matrix(4), 4))
print(e_value(4))
print(diagonal(4))

[[0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]
 [1. 0. 0. 0.]]
True
True
[-1.+0.j  0.+1.j  0.-1.j  1.+0.j]
False
